version: '3.7'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: 
      - sh
      - -c
      - |
        php bin/console doctrine:migrations:migrate --no-interaction
        composer require symfony/debug-bundle --dev
        php -S localhost:9000 -t /var/www/html/
    volumes:
      - src:/var/www/html
      - ./symfony/.env:/var/www/html/.env
    ports:
      - 9000:9000
    depends_on:
      - postgres
    links:
      - postgres
  nginx:
    image: nginx:1.21.1-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    links:
      - php-fpm

volumes:
  data:
  src: